compute-resource:
  refresh: 10
  files:
    protocol: sftp
    location: login01.binac.uni-tuebingen.de
    path: /home/$CERISE_USERNAME/.cerise

  jobs:
    protocol: ssh
    location: login01.binac.uni-tuebingen.de
    scheduler: torque
    cwl-runner: $CERISE_API_FILES/cerise/cwltiny.py
    slots-per-node: 4
    queue-name: short
